name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: xcodebuild -project PrivilegedTaskExample/PrivilegedTaskExample.xcodeproj -scheme PrivilegedTaskExample build
