name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: xcodebuild -project PrivilegedTaskExample/PrivilegedTaskExample.xcodeproj -scheme PrivilegedTaskExample build
